Strong naming consent client
kmdlogic/kmd-logic-consent-client pull request #4
Opened 2021-07-22 05:51 UTC by NakulSeerpu

For better compatibility with .NET Framework public KMD Logic assemblies will be strongly named. The private key will be included in the repo as we're not using it for any security related stuff.

2021-07-27 13:06 UTC, Araballi commented on Directory.Build.props
>      <RepositoryUrl>https://github.com/kmdlogic/kmd-logic-consent-client</RepositoryUrl>
`<GenerateAssemblyVersionAttribute>true</GenerateAssemblyVersionAttribute>` change is missing

2021-07-27 13:08 UTC, Araballi requested changes
Do Build.props files has missing changes

2021-07-27 13:16 UTC, NakulSeerpu commented on Directory.Build.props
>      <RepositoryUrl>https://github.com/kmdlogic/kmd-logic-consent-client</RepositoryUrl>
Fixed

2021-07-28 04:31 UTC, Araballi approved these changes
LGTM

2021-07-28 13:17 UTC, merged